# Generated by Django 4.0.6 on 2022-07-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_important_imp_status_problem_problem_solved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='file',
            field=models.FileField(max_length=1000, null=True, upload_to='solutions'),
        ),
    ]
